cmake_minimum_required(VERSION 4.1)
project(AT32F423CCT7_WorkBench C)

set(CMAKE_C_STANDARD 11)

include_directories(libraries/cmsis/cm4/core_support)
include_directories(libraries/cmsis/cm4/device_support)
include_directories(libraries/drivers/inc)
include_directories(project/inc)

add_executable(AT32F423CCT7_WorkBench
        libraries/cmsis/cm4/core_support/arm_common_tables.h
        libraries/cmsis/cm4/core_support/arm_common_tables_f16.h
        libraries/cmsis/cm4/core_support/arm_const_structs.h
        libraries/cmsis/cm4/core_support/arm_const_structs_f16.h
        libraries/cmsis/cm4/core_support/arm_helium_utils.h
        libraries/cmsis/cm4/core_support/arm_math.h
        libraries/cmsis/cm4/core_support/arm_math_f16.h
        libraries/cmsis/cm4/core_support/arm_math_memory.h
        libraries/cmsis/cm4/core_support/arm_math_types.h
        libraries/cmsis/cm4/core_support/arm_math_types_f16.h
        libraries/cmsis/cm4/core_support/arm_mve_tables.h
        libraries/cmsis/cm4/core_support/arm_mve_tables_f16.h
        libraries/cmsis/cm4/core_support/arm_vec_math.h
        libraries/cmsis/cm4/core_support/arm_vec_math_f16.h
        libraries/cmsis/cm4/core_support/cmsis_armcc.h
        libraries/cmsis/cm4/core_support/cmsis_armclang.h
        libraries/cmsis/cm4/core_support/cmsis_armclang_ltm.h
        libraries/cmsis/cm4/core_support/cmsis_compiler.h
        libraries/cmsis/cm4/core_support/cmsis_gcc.h
        libraries/cmsis/cm4/core_support/cmsis_iccarm.h
        libraries/cmsis/cm4/core_support/cmsis_version.h
        libraries/cmsis/cm4/core_support/core_cm4.h
        libraries/cmsis/cm4/core_support/mpu_armv7.h
        libraries/cmsis/cm4/core_support/mpu_armv8.h
        libraries/cmsis/cm4/core_support/pmu_armv8.h
        libraries/cmsis/cm4/device_support/at32f423.h
        libraries/cmsis/cm4/device_support/at32f423_conf_template.h
        libraries/cmsis/cm4/device_support/system_at32f423.c
        libraries/cmsis/cm4/device_support/system_at32f423.h
        libraries/drivers/inc/at32f423_acc.h
        libraries/drivers/inc/at32f423_adc.h
        libraries/drivers/inc/at32f423_can.h
        libraries/drivers/inc/at32f423_crc.h
        libraries/drivers/inc/at32f423_crm.h
        libraries/drivers/inc/at32f423_dac.h
        libraries/drivers/inc/at32f423_debug.h
        libraries/drivers/inc/at32f423_def.h
        libraries/drivers/inc/at32f423_dma.h
        libraries/drivers/inc/at32f423_ertc.h
        libraries/drivers/inc/at32f423_exint.h
        libraries/drivers/inc/at32f423_flash.h
        libraries/drivers/inc/at32f423_gpio.h
        libraries/drivers/inc/at32f423_i2c.h
        libraries/drivers/inc/at32f423_misc.h
        libraries/drivers/inc/at32f423_pwc.h
        libraries/drivers/inc/at32f423_scfg.h
        libraries/drivers/inc/at32f423_spi.h
        libraries/drivers/inc/at32f423_tmr.h
        libraries/drivers/inc/at32f423_usart.h
        libraries/drivers/inc/at32f423_usb.h
        libraries/drivers/inc/at32f423_wdt.h
        libraries/drivers/inc/at32f423_wwdt.h
        libraries/drivers/inc/at32f423_xmc.h
        libraries/drivers/src/at32f423_acc.c
        libraries/drivers/src/at32f423_adc.c
        libraries/drivers/src/at32f423_can.c
        libraries/drivers/src/at32f423_crc.c
        libraries/drivers/src/at32f423_crm.c
        libraries/drivers/src/at32f423_dac.c
        libraries/drivers/src/at32f423_debug.c
        libraries/drivers/src/at32f423_dma.c
        libraries/drivers/src/at32f423_ertc.c
        libraries/drivers/src/at32f423_exint.c
        libraries/drivers/src/at32f423_flash.c
        libraries/drivers/src/at32f423_gpio.c
        libraries/drivers/src/at32f423_i2c.c
        libraries/drivers/src/at32f423_misc.c
        libraries/drivers/src/at32f423_pwc.c
        libraries/drivers/src/at32f423_scfg.c
        libraries/drivers/src/at32f423_spi.c
        libraries/drivers/src/at32f423_tmr.c
        libraries/drivers/src/at32f423_usart.c
        libraries/drivers/src/at32f423_usb.c
        libraries/drivers/src/at32f423_wdt.c
        libraries/drivers/src/at32f423_wwdt.c
        libraries/drivers/src/at32f423_xmc.c
        project/inc/at32f423_conf.h
        project/inc/at32f423_int.h
        project/inc/at32f423_wk_config.h
        project/inc/foc_controller.h
        project/inc/foc_utils.h
        project/inc/simplefoc_c.h
        project/inc/wk_adc.h
        project/inc/wk_dma.h
        project/inc/wk_gpio.h
        project/inc/wk_system.h
        project/inc/wk_tmr.h
        project/inc/wk_usart.h
        project/src/at32f423_int.c
        project/src/at32f423_wk_config.c
        project/src/foc_controller.c
        project/src/foc_utils.c
        project/src/main.c
        project/src/simplefoc_c.c
        project/src/wk_adc.c
        project/src/wk_dma.c
        project/src/wk_gpio.c
        project/src/wk_system.c
        project/src/wk_tmr.c
        project/src/wk_usart.c
        project/inc/drv8311_config.h
        project/inc/hal_interface.h
        project/src/debug_serial.c
        project/inc/debug_serial.h)
